blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^blog/$', views.index, name='index'),
    url(r'^blog/(?P<blog_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^blog/(?P<blog_id>[0-9]+)/comment_submit/$', views.comment_submit, name='comment_submit'),
    url(r'^blog/blog_entry/$', views.blog_entry, name='blog_entry'),
]

# 127.0.0.1/blog

    # url(r'^tasks/(?P<name_id>[0-9]+)/edit/$', views.taskedit, name='taskedit'),
    # 127.0.0.1/tasks/1/edit
    # url(r'^tasks/(?P<name_id>[0-9]+)/$', views.task, name='task'),
    # 127.0.0.1/tasks/1

namelist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # 127.0.0.1/

    url(r'^adress/$', views.adress, name='adress'),
    # 127.0.0.1/adress

    url(r'^adress/(?P<adress_id>[0-9]+)/$', views.adress, name='adress2'),
    # 127.0.0.1/adress/1

    url(r'^adress/edit/(?P<adress_id>[0-9]+)/$', views.adress_edit, name='adress_edit'),
    # 127.0.0.1/adress/edit/1

    url(r'^adress/adress_edit/(?P<adress_id>[0-9]+)/$', views.adress_edit_submit, name='adress_edit_submit'),
    # 127.0.0.1/adress/adress_edit/1

]

namesite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('namelist.urls', namespace="names")),
    url(r'^', include('tasks.urls', namespace="tasks")),
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^', include('weather.urls', namespace="weather")),
    url(r'^', include('hackernews.urls', namespace="hackernews")),
    url(r'^', include('scraper.urls', namespace="scraper")),
    url(r'^', include('bootstrap.urls', namespace="bootstrap")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

namelist/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Name(models.Model):
    first_name =  models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1)

    def __str__(self):
        return self.first_name

class Adress(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    img_house = models.ImageField(upload_to='files',blank=True)
    Name = models.ForeignKey(Name, on_delete=models.CASCADE)

    def __str__(self):
        return self.street

namelist/views.py
from django.shortcuts import render, get_object_or_404
from .models import Name, Adress
from datetime import datetime
import datetime
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    names = Name.objects.all()
    return render(request, 'namelist/index.html', {'names' : names, 'time':time()})

def adress(request, adress_id=1):
    adress = get_object_or_404(Adress, pk=adress_id)
    fulladress = 'Holland' + ' ' + adress.city + ' ' + adress.street

    return render(request, 'namelist/adress.html', {'adress': adress, 'time':time(), 'fulladress': fulladress})

def adress_edit(request, adress_id):
    adress = Adress.objects.get(pk=adress_id)
    return render(request, 'namelist/adress_edit.html', {'adress': adress, 'time':time()})

def adress_edit_submit(request, adress_id):
    adress = Adress.objects.get(pk=adress_id)
    # Hier moet street en city geupdate worden.. Hoe?
    adress.street = request.POST['street']
    adress.city = request.POST['city']
    adress.save()
    return HttpResponseRedirect(reverse('names:index'))


# Plaats de tijd in de footer
def time():
    now = datetime.datetime.now()
    t = now.strftime("%Y-%m-%d %H:%M")
    return t

namelist/templates/namelist/adress.html
{% extends 'namelist/base.html' %}
 {% block main_content %}

{% load easy_maps_tags %}
{% easy_map fulladress 250 250 %}

{% if adress %}
     lives at the following addres:<p>
    {{adress.street}} {{adress.city}}

<a href="{% url 'names:adress_edit' adress.id %}">Edit</a>

{% else %}
    <p>You dont have any adresses please add some</p>

{% endif %}


{% endblock %}

namelist/templates/namelist/adress_edit.html
{% extends 'namelist/base.html' %}
 {% block main_content %}

Dit is de tempate waar we {{ adress.street }} {{ adress.city }} gaan editten

<p>
Plaatje --> /media/{{adress.img_house}}<br>
Image --> <img src="/media/{{adress.img_house}}", alt="Plaatje" width="40" height="40">


<form action = "{% url 'names:adress_edit_submit' adress.id %}" method="POST">
    {% csrf_token %}
<input type="text" value="{{ adress.street }}" name="street" width="200"><br>
<input type="text" value="{{ adress.city }}" name="city" width="200">



    <input type="submit">

</form>

{% endblock %}

namelist/templates/namelist/base.html
{% load staticfiles  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adres Tasklist suite</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href= "{% static 'namelist/style.css' %}" />
</head>
<body>
<div class="container">
<nav class="navbar navbar-inverse">


    <ul class="nav navbar-nav">
      <li><A Href="{% url 'names:index' %}">Home</A></li>
      <li><A Href="{% url 'tasks:index' %}">Tasks</A></li>
      <li><A Href="{% url 'blog:index' %}">Blog</A></li>
      <li><A Href="{% url 'weather:index' %}">Weatherapp API</A></li>
      <li><A Href="{% url 'hackernews:index' %}">Hackernews API</A></li>
      <li><A Href="{% url 'scraper:index' %}">Scraper</A></li>
      <li><A Href="{% url 'bootstrap:index' %}">Bootstrap</A></li>
    </ul>

</nav>
</div>









<div class="container" style="margin-left:20px;">



<div class="row" style="width: 100%;">{% block main_content %}
{% endblock %}</div>

{% include 'namelist/footer.html' %}
</div>
    <!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

namelist/templates/namelist/footer.html
<p>
    <hr>
        | <A Href="{% url 'names:index' %}">Home</A> | {{time}}
    <hr>

namelist/templates/namelist/index.html
{% extends 'namelist/base.html' %}
 {% block main_content %}
{% load static%}


<img height="100" width="100" src="{% static 'namelist/images/1.png' %}"><p>
<b>Mijn eerste app</b>

<table class="CSS_Table_Example">
    {% for n in names %}
    <tr>
        <td> {{n.first_name}} {{n.last_name}} </td><td> <a href="/tasks/{{n.id}}">[Tasks]</a>

          {% for a in n.adress_set.all %}

        </td>
         <td> <a href="{% url 'names:adress2' a.id %}">[Adres]</a></td></tr>

          {% endfor %}
    {% endfor %}

</table>


{% endblock %}