blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^blog/$', views.index, name='index'),
    url(r'^blog/(?P<blog_id>[0-9]+)/$', views.comment, name='comment'),
    url(r'^blog/(?P<blog_id>[0-9]+)/comment_submit/$', views.comment_submit, name='comment_submit'),
    url(r'^blog/blog_entry/$', views.blog_entry, name='blog_entry'),
]

# 127.0.0.1/blog

    # url(r'^tasks/(?P<name_id>[0-9]+)/edit/$', views.taskedit, name='taskedit'),
    # 127.0.0.1/tasks/1/edit
    # url(r'^tasks/(?P<name_id>[0-9]+)/$', views.task, name='task'),
    # 127.0.0.1/tasks/1

namesite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('namelist.urls', namespace="names")),
    url(r'^', include('tasks.urls', namespace="tasks")),
    url(r'^', include('blog.urls', namespace="blog")),
    url(r'^', include('weather.urls', namespace="weather")),
    url(r'^', include('hackernews.urls', namespace="hackernews")),
    url(r'^', include('scraper.urls', namespace="scraper")),
    url(r'^', include('bootstrap.urls', namespace="bootstrap")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^tasks/$', views.index, name='index'),
    # 127.0.0.1/tasks
    url(r'^tasks/(?P<name_id>[0-9]+)/edit/$', views.taskedit, name='taskedit'),
    # 127.0.0.1/tasks/1/edit
    url(r'^tasks/(?P<name_id>[0-9]+)/$', views.task, name='task'),
    # 127.0.0.1/tasks/1
    url(r'^tasks/(?P<name_id>[0-9]+)/task_new$', views.task_new, name='task_new'),
    # 127.0.0.1/tasks/1/task_new







]

tasks/models.py
from __future__ import unicode_literals
from django.db import models
from namelist.models import Name

# Create your models here.


class Task(models.Model):

    todo = models.CharField(max_length=200)
    done = models.CharField(max_length=100)
    Name = models.ForeignKey(Name)

    def __str__(self):
        return self.todo

tasks/views.py
from django.shortcuts import render
from models import Task
from namelist.models import Name
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.

def index(request):
    print 'hij komt bij INDEX'
    name = Name.objects.all()
    tasks = Task.objects.all()
    return render(request, 'tasks/index.html', {'name' : name, 'tasks': tasks})

def task(request, name_id):
    print 'hij komt bij task'
    tasks = Task.objects.filter(Name_id = name_id)
    return render(request, 'tasks/list.html', {'tasks' : tasks})

def task_new(request, name_id):
    print 'hij komt bij task_new'
    tasks = Task.objects.filter(Name_id=name_id)
    Task.objects.create(todo='', Name_id=name_id)
    return render(request, 'tasks/list.html', {'tasks': tasks})

def taskedit(request, name_id):
    r = request.POST
    d = dict(r)
    for k,v in d.items():
        try:
            int(k)
            t = Task.objects.get(pk=k)
            t.todo = v[0]
            t.save()
        except:
            pass

    return HttpResponseRedirect(reverse('names:index'))

tasks/templates/tasks/index.html
{% extends 'namelist/base.html' %}
 {% block main_content %}

{% load static %}


<img height="50" width="50" src="{% static 'task/images/list.png' %}"><br>

<b>Overview alle Tasks</b>

<ul>

{% for item in name %}

<li> <a href="/tasks/{{item.id}}">[{{item.first_name}} {{item.last_name}}]</a></li>
    {% for i in tasks %}
    {% if i.Name_id == item.id %}
        {{i.todo}}<br>

    {% endif %}

    {% endfor %}



{% endfor %}


</ul>

{% endblock %}

tasks/templates/tasks/list.html
{% extends 'namelist/base.html' %}
{% block main_content %}

{% load static %}





<img height="50" width="50" src="{% static 'task/images/list.png' %}"><p>

{% if tasks %}


 <form action="{% url 'tasks:taskedit' tasks.0.Name.id %}" method="POST" class="smart-green">
 <h1>Tasks for: {{tasks.0.Name}} {{tasks.0.Name.last_name}}</h1>
 {% csrf_token %}


 {%for item in tasks%}

<input type="text" value="{{item.todo}}" name="{{item.id}}"><br>
{% endfor %}
 <input type="submit" value="Save edits"><div>
<a href="{% url 'tasks:task_new' tasks.0.Name.id %}">Add task</a>
</div>

 </form>




{%else%}

No tasks available

{% endif %}




 {% endblock %}
</p>